// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ms-inversions/BrutalistTerminal.tsx": () => import("../components/mockups/ms-inversions/BrutalistTerminal.tsx"),
  "./components/mockups/ms-inversions/MorningPaper.tsx": () => import("../components/mockups/ms-inversions/MorningPaper.tsx")
};
